-- MySQL Script generated by MySQL Workbench
-- Sun Feb  6 15:19:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gUMloso
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gUMloso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gUMloso` ;
USE `gUMloso` ;

-- -----------------------------------------------------
-- Table `gUMloso`.`consumidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`consumidor` (
  `consumidorID` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`consumidorID`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `userID_UNIQUE` (`consumidorID` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `gUMloso`.`localizações`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`localizações` (
  `localizationID` INT NOT NULL AUTO_INCREMENT,
  `morada` VARCHAR(100) NOT NULL,
  `latitude` FLOAT NOT NULL,
  `longitude` FLOAT NOT NULL,
  PRIMARY KEY (`localizationID`),
  UNIQUE INDEX `localizationID_UNIQUE` (`localizationID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gUMloso`.`gestores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`gestores` (
  `gestorID` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`gestorID`),
  UNIQUE INDEX `gestorID_UNIQUE` (`gestorID` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp1256;


-- -----------------------------------------------------
-- Table `gUMloso`.`restaurantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`restaurantes` (
  `restaurantID` INT NOT NULL AUTO_INCREMENT,
  `nomeRestaurante` VARCHAR(45) NOT NULL,
  `pontuação` FLOAT NOT NULL DEFAULT 0,
  `contacto` VARCHAR(45) NOT NULL DEFAULT '\"\"',
  `capacidade` INT NOT NULL DEFAULT 0,
  `localizationID` INT NOT NULL,
  `gestorID` INT NOT NULL,
  PRIMARY KEY (`restaurantID`),
  UNIQUE INDEX `restaurantID_UNIQUE` (`restaurantID` ASC) VISIBLE,
  UNIQUE INDEX `nomeRestaurante_UNIQUE` (`nomeRestaurante` ASC) VISIBLE,
  INDEX `fk_restaurante_localização1_idx` (`localizationID` ASC) VISIBLE,
  INDEX `fk_restaurantes_gestores1_idx` (`gestorID` ASC) VISIBLE,
  CONSTRAINT `fk_restaurante_localização1`
    FOREIGN KEY (`localizationID`)
    REFERENCES `gUMloso`.`localizações` (`localizationID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_restaurantes_gestores1`
    FOREIGN KEY (`gestorID`)
    REFERENCES `gUMloso`.`gestores` (`gestorID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gUMloso`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`reviews` (
  `reviewID` INT NOT NULL AUTO_INCREMENT,
  `stars` INT NOT NULL,
  `descrição` VARCHAR(500) NULL,
  `restaurantID` INT NOT NULL,
  PRIMARY KEY (`reviewID`),
  UNIQUE INDEX `reviewID_UNIQUE` (`reviewID` ASC) VISIBLE,
  INDEX `fk_review_restaurante1_idx` (`restaurantID` ASC) VISIBLE,
  CONSTRAINT `fk_review_restaurante1`
    FOREIGN KEY (`restaurantID`)
    REFERENCES `gUMloso`.`restaurantes` (`restaurantID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gUMloso`.`reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`reservas` (
  `reservaID` INT NOT NULL AUTO_INCREMENT,
  `diaHora` DATETIME NOT NULL,
  `numeroDePessoas` INT NOT NULL,
  `consumidorID` INT NOT NULL,
  `restaurantID` INT NOT NULL,
  PRIMARY KEY (`reservaID`),
  UNIQUE INDEX `reservaID_UNIQUE` (`reservaID` ASC) VISIBLE,
  INDEX `fk_reserva_user1_idx` (`consumidorID` ASC) VISIBLE,
  INDEX `fk_reserva_restaurante1_idx` (`restaurantID` ASC) VISIBLE,
  CONSTRAINT `fk_reserva_user1`
    FOREIGN KEY (`consumidorID`)
    REFERENCES `gUMloso`.`consumidor` (`consumidorID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_restaurante1`
    FOREIGN KEY (`restaurantID`)
    REFERENCES `gUMloso`.`restaurantes` (`restaurantID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gUMloso`.`tiposDeComida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`tiposDeComida` (
  `idtipoDeComida` INT NOT NULL AUTO_INCREMENT,
  `tipoDeComida` VARCHAR(45) NOT NULL,
  `restaurantID` INT NOT NULL,
  PRIMARY KEY (`idtipoDeComida`),
  UNIQUE INDEX `idtipoDeComida_UNIQUE` (`idtipoDeComida` ASC) VISIBLE,
  INDEX `fk_tipoDeComida_restaurante1_idx` (`restaurantID` ASC) VISIBLE,
  CONSTRAINT `fk_tipoDeComida_restaurante1`
    FOREIGN KEY (`restaurantID`)
    REFERENCES `gUMloso`.`restaurantes` (`restaurantID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gUMloso`.`imagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`imagens` (
  `idimagem` INT NOT NULL AUTO_INCREMENT,
  `restaurantID` INT NOT NULL,
  `imagem` LONGBLOB NOT NULL,
  PRIMARY KEY (`idimagem`),
  UNIQUE INDEX `idimagem_UNIQUE` (`idimagem` ASC) VISIBLE,
  INDEX `fk_imagem_restaurante1_idx` (`restaurantID` ASC) VISIBLE,
  CONSTRAINT `fk_imagem_restaurante1`
    FOREIGN KEY (`restaurantID`)
    REFERENCES `gUMloso`.`restaurantes` (`restaurantID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gUMloso`.`horáriosDeFuncionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`horáriosDeFuncionamento` (
  `idhorárioDeFuncionamento` INT NOT NULL AUTO_INCREMENT,
  `abertura` INT NOT NULL,
  `fecho` INT NOT NULL,
  `diaDaSemana` TINYINT NOT NULL,
  `restaurantID` INT NOT NULL,
  PRIMARY KEY (`idhorárioDeFuncionamento`),
  UNIQUE INDEX `idhorárioDeFuncionamento_UNIQUE` (`idhorárioDeFuncionamento` ASC) VISIBLE,
  INDEX `fk_horárioDeFuncionamento_restaurante1_idx` (`restaurantID` ASC) VISIBLE,
  CONSTRAINT `fk_horárioDeFuncionamento_restaurante1`
    FOREIGN KEY (`restaurantID`)
    REFERENCES `gUMloso`.`restaurantes` (`restaurantID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gUMloso`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gUMloso`.`favoritos` (
  `consumidorID` INT NOT NULL,
  `restaurantID` INT NOT NULL,
  INDEX `fk_user_has_restaurante_restaurante1_idx` (`restaurantID` ASC) VISIBLE,
  PRIMARY KEY (`consumidorID`, `restaurantID`),
  CONSTRAINT `fk_user_has_restaurante_user1`
    FOREIGN KEY (`consumidorID`)
    REFERENCES `gUMloso`.`consumidor` (`consumidorID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_restaurante_restaurante1`
    FOREIGN KEY (`restaurantID`)
    REFERENCES `gUMloso`.`restaurantes` (`restaurantID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
